name: Test
run-name: ${{ github.actor }} is testing out Github Actions

on: 
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Repository
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: State Person
        run: echo "Build started by ${{ github.event_name }}"

      - name: Building Project
        run: sh .github/scripts/build.sh

      - name: Upload Build Files
        uses: actions/upload-pages-artifact@v3
        with:
          name: files
          path: ./dist

  deploy:
    name: Deploy
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy Site
        id: deployment
        uses: actions/deploy-pages@v4 
